### ISSUE TITLE
使用链接卡片生成的多个HTML块在水平合并为超级块时，依旧占据100%宽度

### ISSUE THREAD

**Issue by StarDustSheep** [zuoez02/siyuan-plugin-card-link#1]
![image](https://github.com/zuoez02/siyuan-plugin-card-link/assets/114859111/0b8c1d2a-2f32-4cd9-bc86-c2e71565c37b)
期望目标：能通过水平合并多个链接卡片，在同一行中并列多个链接卡片

**Comment by zuoez02** [comment]
跟你的分辨率有关，低分辨率下思源自动把水平布局给垂直了，宽的时候没问题
![image](https://github.com/zuoez02/siyuan-plugin-card-link/assets/4801955/2999117e-2bb1-4e12-8c45-ac5a8772b879)
