### ISSUE TITLE
获取到的卡片链接的图片，直接顶到的最上层

### ISSUE THREAD

**Issue by ccdyd** [zuoez02/siyuan-plugin-card-link#2]
![PixPin_2023-12-09_22-45-40](https://github.com/zuoez02/siyuan-plugin-card-link/assets/87569954/dd9c5686-421b-43bd-a82c-db0b85e92634)
不清楚是哪里出了问题

**Comment by zuoez02** [comment]
我这里默认主题没有复现这个问题，最新版本2.11.1

**Comment by ccdyd** [comment]
> 我这里默认主题没有复现这个问题，最新版本2.11.1

![image](https://github.com/zuoez02/siyuan-plugin-card-link/assets/87569954/81505370-10c8-4a95-9f87-5c6eb4f7ff7c)
还是不行，几个主题都切换了，图片上有6万字的那个是我刚添加的

**Comment by ccdyd** [comment]
> 我这里默认主题没有复现这个问题，最新版本2.11.1
我好像找到原因了，卡片链接和链接图标这两个插件不能同时开，开了就会出现，图片被顶到顶层了，这是个什么bug...
![image](https://github.com/zuoez02/siyuan-plugin-card-link/assets/87569954/36d94154-60a4-405f-910f-2f018364b12b)

**Comment by ccdyd** [comment]
> 我这里默认主题没有复现这个问题，最新版本2.11.1

![image](https://github.com/zuoez02/siyuan-plugin-card-link/assets/87569954/398311d4-b68c-4f3a-bf6a-72ac6710c277)
重启思源笔记后，又变回来了，依旧是图片被顶到顶层了，也是最新版本2.11.1，而且点击顶层图片是可以直接跳转。

**Comment by zuoez02** [comment]
这个得调试了，我这复现不出来，不好意思

**Comment by ccdyd** [comment]
> 这个得调试了，我这复现不出来，不好意思

复现出来了，不清楚这个咋跟挖空冲突了，只要切换下挖空，他就不显示了，但是每次打开软件都要切换

![PixPin_2023-12-11_16-04-37](https://github.com/zuoez02/siyuan-plugin-card-link/assets/87569954/ae42bd6d-3379-4d5f-8132-9d99c81cbd10)

**Comment by zuoez02** [comment]
Resolved in v0.1.1
